### ISSUE TITLE
No logging or comms

### ISSUE THREAD

**Issue by thenumbers1** [DVMProject/dvmhost#38] opened 2023-07-30 04:22 UTC
Running the build from 7/28/23, no sign of acknowledgement of any system activity in the console after "Host is up and running." Tried in P25 Trunked, DMR T2 and DMR T3. P25 radios show no comms. DMR radios will not start a voice call. Showing BER in calibrate mode, so I assume it's not a hardware issue. Unsure what the cause is. As far as control channel goes, the control channels work fine and I confirmed with an SDR.

**Comment by jelimoore** [comment] 2023-07-30 04:37
Closing due to inability to reproduce from multiple setups.

**Closed by jelimoore** 2023-07-30 04:37 UTC
